import type { NextPage } from 'next';
import Head from 'next/head';

import ModalComponent from "./components/modal.component";
import UsersComponent from "./components/users.component";
import {Container} from "react-bootstrap";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ModalComponent />
        <UsersComponent />
      </main>
    </Container>
  )
}

export default Home
