import { ID, Int, Field, ObjectType } from '@nestjs/graphql';

@ObjectType()
export class AnagramCount {
  @Field(() => String, { description: 'One of the multiple anagrams as key' })
  key: string;
  @Field(() => Int, { description: 'count of anagrams' })
  count: number;

  constructor(key: string, count: number) {
    this.key = key;
    this.count = count;
  }
}

@ObjectType()
export class Anagram {
  @Field(() => ID, { description: 'primary key autogenerated' })
  id: string;
  @Field(() => Int, { description: 'foreign key id of the related user' })
  user_id: number;
  @Field(() => Object, { description: 'anagrams count' })
  anagram_map: [AnagramCount];
}
